version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres_boilerplate
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: boilerplate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.api
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    command: "turbo dev"

volumes:
  postgres_data:
