FROM node:18 AS builder

WORKDIR /app
COPY . .

RUN npm install -g pnpm

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm install
RUN pnpm build

FROM node:18

WORKDIR /app

RUN npm install -g pnpm

COPY --from=builder /app .

EXPOSE 8000

CMD ["turbo", "dev"]
